version: '3.8'

services:
  db:
    image: postgres
    container_name: trading_bot_db
    environment:
      - POSTGRES_DB=trading_bot_development
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis
    container_name: trading_bot_redis
    ports:
      - "6379:6379"